// foree-browser/src/routes/(app)/(auth)/(onboard_layout)/onboarding/+page.svelte
<script lang="ts">
    import { enhance } from "$app/forms"
    import MultiStepForm from "$lib/components/MultiStepForm.svelte"

    const phoneNumberPattern = "[0-9]{3}-[0-9]{3}-[0-9]{4}"

    let countries = $state([
		{
			isoCode:  "CA",
			name:  "Canada",
		},
		{
			isoCode:  "PK",
			name:  "Pakistan",
		},
		{
			isoCode:  "US",
			name:  "United States of America",
		},
	]);

    let submitting = $state(false)
    let createUserForm = $state<CreateUserData>({
        firstName: "",
        middleName: "",
        lastName: "",
        dob: "",
        pob: "",
        nationality: "",
        address1: "",
        address2: "",
        city: "",
        province: "",
        country: "",
        postalCode: "",
        phoneNumber: "",
        identificationType: "",
        identificationValue: "",
    })
    let createUserErr = $state<CreateUserError>({})

    $inspect(createUserForm)
</script>

{#snippet step1()}
    <div class="step">
        <h2>Let's Get to Know You!</h2>
        <p>Please enter your full legal name se we can begin setting up your account.</p>
        <div class="name-fields">
            <div class="firstname">
                <label for="firstName">First Name</label>
                <input bind:value={createUserForm.firstName} type="text" id="firstName" name="firstName" required>
                {#if !!createUserErr?.firstName}
                    <p class="input-error">{createUserErr.firstName}</p>
                {/if}
            </div>
            <div class="middleName">
                <label for="middleName">Middle Name</label>
                <input bind:value={createUserForm.middleName} type="text" id="middleName" name="middleName">
                {#if !!createUserErr?.middleName}
                    <p class="input-error">{createUserErr.middleName}</p>
                {/if}
            </div>
            <div class="lastName">
                <label for="lastName">Last Name</label>
                <input bind:value={createUserForm.lastName} type="text" id="lastName" name="lastName" required>
                {#if !!createUserErr?.lastName}
                    <p class="input-error">{createUserErr.lastName}</p>
                {/if}
            </div>
        </div>
    </div>
{/snippet}

{#snippet step2()}
    <div class="step">
        <h2>Your Residential Address and Phone Number</h2>
        <p>We require this information to continue setting up your Foree Remittance account.</p>
        <div class="address-fields">
            <div class="country">
                <label for="country">Country</label>
                <!-- <input bind:value={createUserForm.country} type="country" id="country" name="country" required> -->
                 <select
                    bind:value={createUserForm.country}
                    id="country"
                    name="country"
                    required
                 >
                    {#each countries as country}
                        <option value={country.isoCode}>{country.name}</option>
                    {/each}
                 </select>
                {#if !!createUserErr?.country}
                    <p class="input-error">{createUserErr.country}</p>
                {/if}
            </div>
            <div class="address1">
                <label for="address1">Address</label>
                <input bind:value={createUserForm.address1} type="text" id="address1" name="address1" required>
                {#if !!createUserErr?.address1}
                    <p class="input-error">{createUserErr.address1}</p>
                {/if}
            </div>
            <div class="address2">
                <label for="address2">Address Line2(Apt,suite,etc.)</label>
                <input bind:value={createUserForm.address2} type="text" id="address2" name="address2">
                {#if !!createUserErr?.address2}
                    <p class="input-error">{createUserErr.address2}</p>
                {/if}
            </div>
            <div class="city">
                <label for="city">City</label>
                <input bind:value={createUserForm.city} type="text" id="city" name="city" required>
                {#if !!createUserErr?.city}
                    <p class="input-error">{createUserErr.city}</p>
                {/if}
            </div>
            <div class="province">
                <label for="province">province</label>
                 <select
                    bind:value={createUserForm.province}
                    id="province"
                    name="province"
                    required
                 >
                    {#each countries as province}
                        <option value={province.isoCode}>{province.name}</option>
                    {/each}
                 </select>
                {#if !!createUserErr?.province}
                    <p class="input-error">{createUserErr.province}</p>
                {/if}
            </div>
            <div class="postal-code">
                <label for="postalCode">Postal Code</label>
                <input bind:value={createUserForm.postalCode} type="text" id="postalCode" name="postalCode" required>
                {#if !!createUserErr?.postalCode}
                    <p class="input-error">{createUserErr.postalCode}</p>
                {/if}
            </div>
            <div class="phone-number">
                <label for="phoneNumber">Phone Number</label>
                <input 
                    bind:value={createUserForm.phoneNumber} 
                    type="text" 
                    id="phoneNumber" 
                    name="phoneNumber"
                    placeholder="000-000-0000"
                    pattern={phoneNumberPattern}
                    required
                >
                {#if !!createUserErr?.phoneNumber}
                    <p class="input-error">{createUserErr.phoneNumber}</p>
                {/if}
            </div>
        </div>
    </div>
{/snippet}

{#snippet step3()}
    <div class="step">
        <h2>Personal Details</h2>
        <p>Almost done! Infomation below is requested by XXXXXX Bank of XXXXXXX, our Foree Remittance payout partner, in order to process your transfers under Pkakistani regulatory guidelines</p>
        <div class="personal-fields">
            <div class="dob">
                <label for="dob">Date of Birth</label>
                <input 
                    bind:value={createUserForm.dob}
                    type="date" 
                    id="dob" 
                    name="dob"
                    required
                >
                {#if !!createUserErr?.dob}
                    <p class="input-error">{createUserErr.dob}</p>
                {/if}
            </div>
            <div class="pob">
                <label for="country">Place of Birth</label>
                <!-- <input bind:value={createUserForm.country} type="country" id="country" name="country" required> -->
                 <select
                    bind:value={createUserForm.pob}
                    id="country"
                    name="country"
                    required
                 >
                    {#each countries as country}
                        <option value={country.isoCode}>{country.name}</option>
                    {/each}
                 </select>
                {#if !!createUserErr?.country}
                    <p class="input-error">{createUserErr.country}</p>
                {/if}
            </div>
            <div class="nationality">
                <label for="nationality">Nationality</label>
                <!-- <input bind:value={createUserForm.nationality} type="nationality" id="nationality" name="nationality" required> -->
                 <select
                    bind:value={createUserForm.nationality}
                    id="nationality"
                    name="nationality"
                    required
                 >
                    {#each countries as nationality}
                        <option value={nationality.isoCode}>{nationality.name}</option>
                    {/each}
                 </select>
                {#if !!createUserErr?.nationality}
                    <p class="input-error">{createUserErr.nationality}</p>
                {/if}
            </div>
            <div class="identification-type">
                <label for="identificationType">Identification Document Type</label>
                <!-- <input bind:value={createUserForm.identificationType} type="identificationType" id="identificationType" name="identificationType" required> -->
                 <select
                    bind:value={createUserForm.identificationType}
                    id="identificationType"
                    name="identificationType"
                    required
                 >
                    {#each countries as identificationType}
                        <option value={identificationType.isoCode}>{identificationType.name}</option>
                    {/each}
                 </select>
                {#if !!createUserErr?.identificationType}
                    <p class="input-error">{createUserErr.identificationType}</p>
                {/if}
            </div>
            <div class="identification-value">
                <label for="identificationValue">Identification Number</label>
                <input 
                    bind:value={createUserForm.identificationValue}
                    id="identificationValue" 
                    name="identificationValue"
                    required
                >
                {#if !!createUserErr?.identificationValue}
                    <p class="input-error">{createUserErr.identificationValue}</p>
                {/if}
            </div>
        </div>
    </div>
{/snippet}
    
<main>
    <MultiStepForm 
        steps={[step1, step2, step3]}
        method="POST"
    >
    </MultiStepForm>
</main>

<style>
    main {
        width: 95%;
        max-width: 900px;
        margin: 3.5rem auto;

        @media (max-width: 700px) {
            margin: 2.5rem auto;
        }
    }

    .step {
        & > p:first-of-type {
            text-align: center;
            margin: 1.5rem 0;
        }

        & > h2:first-of-type {
            text-align: center;
            margin: 0;
        }

        @media (max-width: 400px) {
            & > h2:first-of-type {
                font-size: 1em;
            }
        }
    }

    .name-fields{
        display: grid;
        gap: 1rem;
        grid-template-columns: repeat(3, 1fr);
        @media (max-width: 700px) {
            & {
                grid-template-columns: 1fr;
            }
        }
    }

    .address-fields {
        display: grid;
        grid-template-columns: repeat(12, 1fr);
        gap: 1rem;

        .country {
            grid-column: 1 / span 12;
        }

        .address1 {
            grid-column: 1 / span 8;
        }

        .address2 {
            grid-column: 9 / 13;
        }

        .city {
            grid-column: 1 / 5;
        }

        .province {
            grid-column: 5 / 9;
        }

        .postal-code {
            grid-column: 9 / 13;
        }

        .phone-number {
            grid-column: 1 / span 12;
        }

        @media (max-width: 700px) {
            .address1 {
                grid-column: 1 / span 12;
            }

            .address2 {
                grid-column: 1 / span 12;
            }
            .city {
                grid-column: 1 / span 12;
            }

            .province {
                grid-column: 1 / span 12;
            }

            .postal-code {
                grid-column: 1 / span 12;
            }
        }
    }

    .personal-fields {
        display: grid;
        gap: 1rem;
    }
</style>

// foree-mobile/app/(auth)/onboarding.jsx
import { View, Text, ScrollView } from 'react-native'
import { SafeAreaView } from 'react-native'
import React, { useState } from 'react'
import MultiStepForm from '../../components/MultiStepForm'
import FormField from '../../components/FormField'


const Onboarding = () => {

  const [form, setForm] = useState({
    firstName: '',
    middleName: '',
    lastName: '',
    addressLine1: '',
    addressLine2: '',
    city: '',
    province: '',
    country: 'Canada',
    postalCode: '',
    phoneNumber: '',
    dob: '',
    pob: '',
    nationality: '',
    identificationType: '',
    identificationValue: '',
  })

  const submit = () => {
    setIsSubmitting(true)
    setTimeout(() => {
      setIsSubmitting(false)
      console.log(form)
      // router.replace("/verify_email")
    }, 1000);
  }

  const [isSubmitting, setIsSubmitting] = useState(false)

  const NameField = () => (
    <View>
      <Text className="text-lg font-pbold text-center m-4">Let's Get to Know You!</Text>
      <Text className="font-pregular text-center mb-4">
        Please enter your full legal name so we can begin setting up your account
      </Text>

      <FormField
        title="First Name"
        value={form.firstName}
        handleChangeText={(e) => setForm({
          ...form,
          firstName:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Middle Name"
        value={form.middleName}
        handleChangeText={(e) => setForm({
          ...form,
          middleName:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Last Name"
        value={form.lastName}
        handleChangeText={(e) => setForm({
          ...form,
          lastName:e
        })}
        otherStyles="mt-2"
        keyboardType="ascii-capable"
      />
    </View>
  )

  const AddressField = () => (
    <View>
      <Text className="text-lg font-pbold text-center m-4">Your Residential Address and Phone Number</Text>
      <Text className="font-pregular text-center mb-4">
        We require this information to continue setting up your Foree Remittance account
      </Text>

      <FormField
        title="Address Line 1"
        value={form.addressLine1}
        handleChangeText={(e) => setForm({
          ...form,
          addressLine1:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Address Line 2"
        value={form.addressLine2}
        handleChangeText={(e) => setForm({
          ...form,
          addressLine2:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="City"
        value={form.city}
        handleChangeText={(e) => setForm({
          ...form,
          city:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Province"
        value={form.province}
        handleChangeText={(e) => setForm({
          ...form,
          province:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Country"
        value={form.country}
        handleChangeText={(e) => setForm({
          ...form,
          country:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Postal Code"
        value={form.postalCode}
        handleChangeText={(e) => setForm({
          ...form,
          postalCode:e
        })}
        otherStyles="mt-2"
        keyboardType="ascii-capable"
      />
      <FormField
        title="Phone Number"
        value={form.phoneNumber}
        handleChangeText={(e) => setForm({
          ...form,
          phoneNumber:e
        })}
        otherStyles="mt-2"
        keyboardType="ascii-capable"
      />
    </View>
  )

  const PersonalDetailField = () => (
    <View>
      <Text className="text-lg font-pbold text-center m-4">Personal Details</Text>
      <Text className="font-pregular text-center mb-4">
        Almost done! Infomation below is requested by xxxxx xxxxx of xxxxxxx, our Foree Remittance payout parter, inorder to process your transfers under ...... regulatory guidelines
      </Text>
      <FormField
        title="Date of Birth"
        value={form.dob}
        handleChangeText={(e) => setForm({
          ...form,
          dob:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Place of Birth"
        value={form.pob}
        handleChangeText={(e) => setForm({
          ...form,
          pob:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Nationality"
        value={form.nationality}
        handleChangeText={(e) => setForm({
          ...form,
          nationality:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Identification Document Type"
        value={form.identificationType}
        handleChangeText={(e) => setForm({
          ...form,
          identificationType:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
      <FormField
        title="Identification Number"
        value={form.identificationValue}
        handleChangeText={(e) => setForm({
          ...form,
          identificationValue:e
        })}
        keyboardType="ascii-capable"
        otherStyles="mt-2"
      />
    </View>
  )

  const OnboardingFlow = [
    {
      formView: NameField,
      canGoNext: () => {
        return true
      }
    },
    {
      formView: AddressField,
      canGoNext: () => {
        return true
      }
    },
    {
      formView: PersonalDetailField,
      canGoNext: () => {
        return true
      }
    }
  ]

  return (
    <SafeAreaView className="bg-slate-100">
      <MultiStepForm
        steps={() => OnboardingFlow}
        onSumbit={submit}
      />
      {/* <ScrollView
        className="bg-slate-100"
        automaticallyAdjustKeyboardInsets
      >
        <MultiStepForm/>
      </ScrollView> */}
    </SafeAreaView>
  )
}

export default Onboarding
